### ISSUE TITLE
Netview: using scroll bars removes network from display

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#10]
If you use either the bottom or right side scroll bars the network disappears.  But immediately comes back if you click on one of the right side buttons for the different values to display.  Also comes back if you click the movement controls on the bottom (pan, rotate, etc.).

**Comment by vej** [comment]
I have this same issue, and it appears to happen both on Mac and Windows operating systems.

**Comment by rcoreilly** [comment]
yep, it will be fixed at some point..  the netview uses special optimized rendering so it requires special logic for this case.

**Comment by rcoreilly** [comment]
now fixed.
