### ISSUE TITLE
Font size in interface

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#12]
This may be a GoGi issue, but it would be nice if one could change not just the font, but the font size for the interface.

**Comment by rcoreilly** [comment]
use standard zoom keys (command + or -) and save in gogi prefs.

**Comment by StephenJRead** [comment]
I tried this, but there are a couple of issues currently.
1) As you said, you can use the command and + or - to zoom in or out, but there are two glitches: a) you can save the change, but if you go back to the program window and hit the init button it crashes the program.  It only works if you quit the program and then restart, b) when you do the command key thing, it is frequently the case that the first command goes in the wrong direction, that is the first command + will zoom out and a command - will zoom in.

3) DPI selection.  Although you can change the DPI values in the text box, the Save Zoom button does not save the changes and it just goes back to the previous value

4) Is this documented anywhere?
