### ISSUE TITLE
Broken homepage

### ISSUE THREAD

**Issue by francesshei** [emer/emergent#128]
When trying to access `https://emersim.org/` I get redirected to `http://185.199.111.153` and land on the following error message:

<img width="739" alt="Screenshot 2024-05-09 at 16 42 35" src="https://github.com/emer/emergent/assets/39373100/290b5038-96c9-4abb-8585-954d9844a349">

MacOS 14.2.1, Safari 17.2.1

**Comment by kkoreilly** [comment]
Yep, we are aware of this issue and will work on fixing it.

**Comment by kkoreilly** [comment]
I fixed this; the website should be working now.
