### ISSUE TITLE
Font size change is glitchy

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#13]
I tried the command - and + keys in GoGi preferences, but there are a couple of issues currently.

1) As you said, you can use the command and + or - to zoom in or out, but there are two glitches: a) you can save the change with the Save Zoom button, but if you go back to the program window and hit the Init button it crashes the program. It only works if you quit the program and then restart, b) when you do the command key thing, it is frequently the case that the first command goes in the wrong direction, that is the first command + will zoom out and a command - will zoom in. Any command after that does in the right direction.

2) DPI selection. Although you can change the DPI values in the text box, the Save Zoom button does not save the changes and it just goes back to the previous value

3) Is this documented anywhere?

**Comment by rcoreilly** [comment]
looks like the zoom was a reliable way to trigger a bug I'd been sporadically seeing -- finally got that one!  shouldn't crash.  I can't replicate the wrong-way effect myself.  the std way to do this is use the zoom commands -- if you manually change the dpi then you need to hit the update button.. this is documented in the GoGi widgets demo..

**Comment by rcoreilly** [comment]
assuming all good?  reopen with further comments if not.
