### ISSUE TITLE
When training, buttons for different graphic views largely unresponsive

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#14]
When you start training with ra25, if you click the TrnEpcPlot button to look at that plot, the other buttons, such as NetView and TstTrlPlot are largely unresponsive.  That is you can click on them multiple times and only rarely will they switch you to the relevant plot.  For example, the NetView button is largely unresponsive, once you have switched to TrnEpcPlot. Once you stop training, then the buttons respond normally.

**Comment by rcoreilly** [comment]
yep now fixed.
