### ISSUE TITLE
ra25 crashed when I was clicking through Paramsets

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#16]
I was looking through the various ParamSets in the interface for ra25 and it crashed on me.

**Comment by rcoreilly** [comment]
go should have printed out a stack trace -- please include those as otherwise we can't do anything.  also, if you can make this reproducible, that is the best.

**Comment by StephenJRead** [comment]
Should it have been in the terminal window?  This is what I got when it crashed.

StephenReadsMBP:ra25 read$ ./ra25
OpenGL version 4.1 INTEL-12.8.38
StephenReadsMBP:ra25 read$ ./ra25
OpenGL version 4.1 INTEL-12.8.38
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x45cc080]

goroutine 180 [running]:
image.(*RGBA).Bounds(...)
/usr/local/go/src/image/image.go:72
github.com/goki/gi/gi.ImageClearer<http://github.com/goki/gi/gi.ImageClearer>(0x0, 0x42480000)
/Users/read/go/src/github.com/goki/gi/gi/bitmap.go:232<http://github.com/goki/gi/gi/bitmap.go:232> +0x50
github.com/goki/gi/giv<http://github.com/goki/gi/giv>.(*SliceViewBase).DragNDropStart(0xc01e53d500)
/Users/read/go/src/github.com/goki/gi/giv/sliceviewbase.go:1632<http://github.com/goki/gi/giv/sliceviewbase.go:1632> +0x1af
github.com/goki/gi/giv<http://github.com/goki/gi/giv>.(*SliceViewBase).SliceViewBaseEvents.func6(0x53be900, 0xc01e53d500, 0x53b2e00, 0xc0136b9b00, 0x10, 0x4f81d40, 0xc00cbabc70)
/Users/read/go/src/github.com/goki/gi/giv/sliceviewbase.go:1986<http://github.com/goki/gi/giv/sliceviewbase.go:1986> +0xc5
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*WinEventRecv).Call(...)
/Users/read/go/src/github.com/goki/gi/gi/window.go:1936<http://github.com/goki/gi/gi/window.go:1936>
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).SendEventSignal(0xc0136b9b00, 0x5348a80, 0xc00cbabc70, 0x5cfb3200)
/Users/read/go/src/github.com/goki/gi/gi/window.go:2080<http://github.com/goki/gi/gi/window.go:2080> +0x510
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).DNDStartEvent(0xc0136b9b00, 0xc01e47b3e0)
/Users/read/go/src/github.com/goki/gi/gi/window.go:2954<http://github.com/goki/gi/gi/window.go:2954> +0x10e
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).EventLoop(0xc0136b9b00)
/Users/read/go/src/github.com/goki/gi/gi/window.go:1581<http://github.com/goki/gi/gi/window.go:1581> +0x25b8
created by github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).GoStartEventLoop
/Users/read/go/src/github.com/goki/gi/gi/window.go:787<http://github.com/goki/gi/gi/window.go:787> +0xa7


On Jun 8, 2019, at 11:59 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


go should have printed out a stack trace -- please include those as otherwise we can't do anything. also, if you can make this reproducible, that is the best.

**Comment by rcoreilly** [comment]
yep that is very helpful!  looks like you started dragging an item -- I just changed some of that code so that is a plausible culprit.

**Comment by rcoreilly** [comment]
this should now be fixed -- reopen if not.
