### ISSUE TITLE
Viewing unit specific information, like r.wt, s.wt, etc?

### ISSUE THREAD

**Issue by vej** [emer/emergent#18]
Is there anything in the works to get it so you can view unit specific information in the gui, like before? In the old emergent, as well as viewing activity, input, etc, you could view a unit's receiving weights (r.wt) or sending weights (s.wt). Wondering if that will be possible here. Thanks!

**Comment by rcoreilly** [comment]
yep check out the https://github.com/emer/emergent#todo section for everything on the todo list!

**Comment by vej** [comment]
I missed that bullet, thank you! Glad it's on the list.

**Comment by rcoreilly** [comment]
all working now.
