### ISSUE TITLE
Glitchiness of emergent exe windows in Windows 10

### ISSUE THREAD

**Issue by DhairyyaS** [emer/emergent#19]
I installed the new Go version of Emergent by following the instructions on (https://github.com/emer/emergent/wiki/Install) and while Go and Gogi are installed correctly on my Windows 10 PC, when I build the ra25 example exe in emer/leabra/examlples/ra25 and try to run it via the command line, it doesn't open up the exe window. The window actually remains glitched out and minimized (screenshot attached below) and clicking on the window icon in the toolbar doesn't seem to do anything.

The only way to then force the window open reliably is to go into window's split-screen mode (by, for example, dragging a window to the edge of the screen) and then selecting the 'Leabra Random Associator' window via the split-screen menu which pops up. The exe window then opens up on half the screen and there's no problems after that in rescaling it to fullscreen. I think perhaps the glitchiness has something to go with the initial scaling of the window and how the initial values may not work on all screen resolutions?(mine is 1080p) I wasn't sure if this was just an issue on my computer so I thought to report it. It's possible that if this happens on other people's computers as well, they might think (as I thought) that their emergent/Go/Gogi is not set up correctly when in fact it might be.

![image](https://user-images.githubusercontent.com/6560969/63247945-db76a180-c283-11e9-9c38-5ee21ae29e42.png)

**Comment by StephenJRead** [comment]
One or two of my students in class are having a similar problem with the chapter 2 exercises.

**Comment by rcoreilly** [comment]
Is it possible to use the scaling (control-shift +) to fix this without jumping through all those hoops?  It would be great to get some specs on the relevant monitors (is it with an external monitor?  internal laptop screen?) and attach the "screen info" report from GoGi Preferences here so we can see if there is something obvious in that.

**Comment by StephenJRead** [comment]
My student who had a problem was using an internal laptop screen.  My lg external monitor that was glitchy with mac was set at 1080p just like this window user. Will try to get screen info from misbehaving projects.

Sent from my iPhone

On Jan 22, 2020, at 10:23 PM, rcoreilly <notifications@github.com> wrote:

﻿

Is it possible to use the scaling (control-shift +) to fix this without jumping through all those hoops? It would be great to get some specs on the relevant monitors (is it with an external monitor? internal laptop screen?) and attach the "screen info" report from GoGi Preferences here so we can see if there is something obvious in that.

**Comment by rcoreilly** [comment]
guessing that this is fixed -- reopen if not.
