### ISSUE TITLE
showing s.wt and r.wt not working properly

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#20]
I was trying out the new functionality for looking at s.wt and r.wt and its not working properly.
1) one initial point is that I had to download the changes and rebuild gi for it to recognize the selections.
2) Once I did that, I was playing around with ra25 and it was not behaving properly.  If I set it to show s.wt then when I click on the nodes in the Input layer, I get a single green highlighted node in Hidden1 and then a bunch of red highlighted nodes in Hidden2.(note that not all nodes in the input layer respond to a click)  But if I click on a node in Hidden1 nothing happens.  Then if I click on nodes in Hidden2, I get a response for some of them, but not all of them.  When it works, I get a green highlighted node in the Output layer and the red highlighted nodes in Hidden2 change, but nothing happens in any of the other layers.
3) r.wt has similar problems

**Comment by rcoreilly** [comment]
It might be related to scrolling -- can you resize your window so there is no scrollbar?  for me, if I have the scrollbar, the picking coordinates are off so it selects the wrong units.  looks like we need two columns of unit variables too..

**Comment by StephenJRead** [comment]
I don’t have access to my large screen monitor right now and on my 13 inch laptop I can’t get rid of the scrollbars, so I can’t check right now. Will let you know when I can.


On Aug 20, 2019, at 12:18 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


It might be related to scrolling -- can you resize your window so there is no scrollbar? for me, if I have the scrollbar, the picking coordinates are off so it selects the wrong units. looks like we need two columns of unit variables too..

**Comment by StephenJRead** [comment]
Just tried it with my large screen.  If I can open the project without the scroll bars it behaves properly.  However, if I  shrink the windows, it no longer properly tracks which node is clicked on.

**Comment by StephenJRead** [comment]
Just tried it again with the revision that was just uploaded.  With the revision it works fine as long as there is no right side scroll bar.  However, if you shrink the window, top to bottom, so that the right side scroll bar appears, clicks on nodes are misregistered again.  If I then resize the window so that the right side scroll bar disappears, everything goes back to registering properly

**Comment by rcoreilly** [comment]
all fixed -- need to update goki/gi as well as emer/emergent
