### ISSUE TITLE
Netview window doesn't properly resize to show full extent of bottom page controls

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#24]
I have the net view window open to the full vertical extent of my large scale monitor.  It does not show a right hand scroll bar, but it only shows the top half of the controls at the bottom of the window (rotate, pan, change size, etc.). The controls are functional, but they are hard to read.

**Comment by rcoreilly** [comment]
do you have a bottom scrollbar? I can see that it is not making room for the bottom scrollbar if I have it narrower than width required for top toolbar.

**Comment by StephenJRead** [comment]
Yes.


On Aug 22, 2019, at 1:00 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


do you have a bottom scrollbar? I can see that it is not making room for the bottom scrollbar if I have it narrower than width required for top toolbar.

**Comment by StephenJRead** [comment]
I notice that if I resize the window, by increasing the vertical size, that once the space between the box with all the variables and the Run, Epoch, etc text gets larger than some minimum value the right side scroll bar disappears, but the bottom controls are still cut in half.  If I shrink the window thenat some point when the distance between the variable box and the text gets small enough, then the right scrollbar re appears.  (Does that make sense?)


On Aug 22, 2019, at 1:00 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


do you have a bottom scrollbar? I can see that it is not making room for the bottom scrollbar if I have it narrower than width required for top toolbar.

**Comment by rcoreilly** [comment]
scrollbar behavior fixed in new vulkan model.
