### ISSUE TITLE
Where does one set the minimum sse for stopping and the number of epochs at that minimum?

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#30]
This is a question rather than an issue.  I had two related questions:
1) where do you set the sse criteria for stopping training?
2) where do you set the number of consecutive epochs at that value to stop training?  

Both seem set for projects in chapter 4, but I cannot see where.

**Comment by rcoreilly** [comment]
actually not yet implemented!  on my todo list for this evening :)

**Comment by StephenJRead** [comment]
Okay, thanks! I see you are making considerable progress.



On Sep 5, 2019, at 9:34 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


actually not yet implemented! on my todo list for this evening :)

**Comment by rcoreilly** [comment]
just committed.. NZeroStop and NZero stat.
