### ISSUE TITLE
Window keeps growing when project left open

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#31]
I have noticed that when I leave a project open for a while, such as over night, the window gets very wide, many multiple screen widths wide.  to resize it I need to move the window over and then from the right side keep manually shrinking the width.

**Comment by rcoreilly** [comment]
yeah there is a bug in the underlying glfw toolkit.  been waiting for them to update but not happening -- will probably have to do myself at some point.

**Comment by StephenJRead** [comment]
Okay, just annoying, doesn’t make it unusable.


Sent from my iPad

On Sep 6, 2019, at 11:05 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


yeah there is a bug in the underlying glfw toolkit. been waiting for them to update but not happening -- will probably have to do myself at some point.

**Comment by rcoreilly** [comment]
Duplicate of #15 -- consolidating.
