### ISSUE TITLE
Ubuntu installation failure, leabra/examples/ra25, ext.Floats() used as value

### ISSUE THREAD

**Issue by DanielNScott** [emer/emergent#32]
Hi all, I'm having trouble installing Emergent on my XPS-13 running Ubuntu 16 LTS. I had no issues with GoKi or GoGi, and the widgets built without errors. Go getting leabra (```go get -u github.com/emer/leabra```) did not complain. The error I get is:

```
dan@dan-XPS-13:~/go/src/github.com/emer/leabra/examples/ra25$ go get -u ./...
# github.com/emer/leabra/leabra
../../leabra/layer.go:575:37: not enough arguments in call to ext.Floats
	have ()
	want (*[]float64)
../../leabra/layer.go:575:37: ext.Floats() used as value
```
Additional system info:
```
dan@dan-XPS-13:~/go/src/github.com/emer/leabra/examples/ra25$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
and go version is ```go1.13 linux/amd64```.

Does anyone have suggestions about how to troubleshoot this? From my perspective (knowing nothing about Go) it just looks like it's just a usage issue in the layer.go code, per the error message, but maybe someone who was involved in writing this code can weigh in.

**Comment by StephenJRead** [comment]
Hopefully, Randy will chime in, but in your error description below, it is not clear to me where the following came from.

# github.com/emer/leabra/leabra<http://github.com/emer/leabra/leabra>

  It is not part of the install instructions.

When I run
go get -u ./… alone, everything works and then I do:
go build
And then
./ra25 to run the program.


On Sep 8, 2019, at 2:47 PM, Daniel Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all, I'm having trouble installing Leabra on my XPS-13 running Ubuntu 16 LTS. I had no issues with GoKi or GoGi, and the widgets built without errors. Go getting leabra (go get -u github.com/emer/leabra<http://github.com/emer/leabra>) did not complain. The error I get is:

dan@dan-XPS-13:~/go/src/github.com/emer/leabra/examples/ra25$<http://github.com/emer/leabra/examples/ra25$> go get -u ./...
# github.com/emer/leabra/leabra<http://github.com/emer/leabra/leabra>
../../leabra/layer.go:575:37: not enough arguments in call to ext.Floats
        have ()
        want (*[]float64)
../../leabra/layer.go:575:37: ext.Floats() used as value


Additional system info:

dan@dan-XPS-13:~/go/src/github.com/emer/leabra/examples/ra25$<http://github.com/emer/leabra/examples/ra25$> lsb_release -a
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial


and go version is go1.13 linux/amd64.

Does anyone have suggestions about how to troubleshoot this? From my perspective (knowing nothing about Go) it just looks like it's just a usage issue in the layer.go code, per the error message, but maybe someone who was involved in writing this code can weigh in.

**Comment by rcoreilly** [comment]
your leabra is not updated.  the go get -u ./... *should* have updated it but for some reason it didn't.  how about just trying git pull in leabra?  The signature for Floats changed so it now takes an arg instead of returning it.

current version:
		ext.Floats(&flt)

**Comment by StephenJRead** [comment]
I just tried to update my leabra and got exactly the same error message.  This has never happened before.


On Sep 8, 2019, at 8:55 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


your leabra is not updated. the go get -u ./... should have updated it but for some reason it didn't. how about just trying git pull in leabra? The signature for Floats changed so it now takes an arg instead of returning it.

current version:
ext.Floats(&flt)

**Comment by StephenJRead** [comment]
So a novice question. Which leabra should I be in?  emer/leabra or emer/leabra/leabra


On Sep 8, 2019, at 8:55 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


your leabra is not updated. the go get -u ./... should have updated it but for some reason it didn't. how about just trying git pull in leabra? The signature for Floats changed so it now takes an arg instead of returning it.

current version:
ext.Floats(&flt)

**Comment by rcoreilly** [comment]
oops -- sorry!  It would help if I actually checked that change in.  Now checked in and should work.

**Comment by DanielNScott** [comment]
Confirming it works properly for me now. Thanks!
