### ISSUE TITLE
prjn learn flag can't be turned off when the layers and/or the prjn is off 

### ISSUE THREAD

**Issue by xiaonanl** [emer/emergent#36]
The problem is the turning the learn flag off will only stop learning when the layers and prjn are on. Then everything is off, it will still learn.

**Comment by xiaonanl** [comment]
Ok, even if the learn flag was off, the network will still learn something though very minor. Can't really see from dwt but the test results are different. But the learning when only learn flag is off is much smaller than when both prjn and learn flag are off.

**Comment by rcoreilly** [comment]
I just experimented with ra25 and hip examples, and both obey the Off flag, as in the code below.  And the IsOff() method checks both the prjn Off flag *and* both the send and recv layer Off flags.

However, it is also *definitely* the case that when you turn it off, any residual DWt values will still show up in the display.

So something strange is happening.  we probably need to sit down and debug together.

```Go
// DWt computes the weight change (learning) -- calls DWt method on sending projections
func (ly *Layer) DWt() {
	for _, p := range ly.SndPrjns {
		if p.IsOff() {
			continue
		}
		p.(LeabraPrjn).DWt()
	}
}

// WtFmDWt updates the weights from delta-weight changes -- on the sending projections
func (ly *Layer) WtFmDWt() {
	for _, p := range ly.SndPrjns {
		if p.IsOff() {
			continue
		}
		p.(LeabraPrjn).WtFmDWt()
	}
}
```

**Comment by xiaonanl** [comment]
i'm sure it's not just a display only problem as the test results are
different. But for the display, if the absolute scale for the color bar is
updated immediately after clicking each node (e.g from min -x to min 0),
dwt seems display correctly.

**Comment by xiaonanl** [comment]
I can try to call DWt and WtFmDWt methods on individual layers rather than at the whole network to isolate which is the layer/prjn that causes the problem.
________________________________

**Comment by rcoreilly** [comment]
can you add print statements in the DWt method after the IsOff() continue statement to verify that it is going into that code?  something is very strange if so as those are really basic functions!

**Comment by rcoreilly** [comment]
ps I will be avail after the eeg meeting to go over

**Comment by xiaonanl** [comment]
Just print()?
I'm sure whether i can make the eeg meeting today but will be
available after 4. Are you coming back to cns after the eeg meeting?

**Comment by rcoreilly** [comment]
print with name of prjn: `fmt.Printf("dwt on: %v\n", pj.Nm)`

yep I'll come back to cns

**Comment by xiaonanl** [comment]
ok, i found out part of the problem. when training the second part of the
model, it still calls wtfmdwt at the beginning which is based on the dwt
from training of the last trial of the first part of the model so it
slightly updated the untrained part. this explains a large portion of the
difference but still not 100%. The rest is very minor though.

But, it's still try that the layer and the learn flag can't be off at the
same time. it seems one is overwrite the other. will test printing after
lab meeting.

**Comment by xiaonanl** [comment]
Closing this one as well.
