### ISSUE TITLE
test with the same model with the same weights will show different results

### ISSUE THREAD

**Issue by xiaonanl** [emer/emergent#37]
I'm create a separate issue here because this seems a different problem. Testing with exact the same model can show slightly different results each time, as shown in SSE and other stats. Might be a random stat issue?

**Comment by rcoreilly** [comment]
do you have the threading turned on?  probably b/c the original hip example does.  Try commenting out those lines and let's see if that's it? 

```Go
	// using 3 threads :)
	dg.SetThread(1)
	ca3.SetThread(2)
	ca1.SetThread(3)
```

when using threads, subtle random diffs can emerge due to order of operations diffs in aggregating results -- floating point roundoffs etc.

**Comment by xiaonanl** [comment]
I did a quick test commenting out thread but it still showed minor
differences in SSE etc. This is probably not a big issue but strange. And
when debugging #36, it's useful to guarantee each test returns exactly
the same results to check whether flag off will prevent learning. I tried
the hip example as well and each test returns slightly difference SSE as
well.

**Comment by rcoreilly** [comment]
@xiaonanl can you confirm that fixing the layer expected activity level (Layer.Inhibi.ActAvg.Fixed = true) produces reliable testing results etc?

**Comment by xiaonanl** [comment]
Yes this is fixed. I'm closing this issue.

**Comment by xiaonanl** [comment]
Can actavg estimated from a lesined model be safely used in a full model and vice versa? Presumably a layer with four input connections needs a different actavg than one with two input. Does this difference matter at all or different actavg needs to be estimated based on the connections?
________________________________

**Comment by rcoreilly** [comment]
it is just about the layer activation so connections probably shouldn't make that much difference.  and getting it exactly right is not critical -- it just scales layer Ge values which you should look at as the model runs -- if they look significantly low or high in a given layer, then adjusting for layers that *send* to that layer can help.
