### ISSUE TITLE
Mouse location registered by emergent does not correspond with screen location

### ISSUE THREAD

**Issue by DanielNScott** [emer/emergent#42]
In my copy of emergent (updated just now with `go get -u ./...`) the mouse location is not registered properly. This screenshot illustrates the problem: 

![Bad pointer](https://user-images.githubusercontent.com/7492269/71280627-bc6b4780-2329-11ea-904f-5d77531a05d7.png)

The "All parameters" button is highlighted even though the mouse is upwards and to the left of the button. Maybe this is also related to the poor default resolution on my machine? In case it's relevant information, my display is set to 1920:1080, but the default resolution seems to be poor regardless of my settings. Using ctrl - to change the emergent zoom doesn't resolve the pointer issue.

**Comment by rcoreilly** [comment]
Will be fixing this very soon: it is issue #310 at https://github.com/goki/gi/issues/310

**Comment by rcoreilly** [comment]
now fixed.
