### ISSUE TITLE
Netview - Self projection not revealed by receive wts or send wts

### ISSUE THREAD

**Issue by rohrlich** [emer/emergent#47]
I've looked with the debugger and the a2d -> a2d prjn in my model is definitely added and the sender is correct. So, maybe netview isn't showing self connections?

**Comment by rcoreilly** [comment]
first: your code seems to not be updated.  when you click on a layer, it should pull up an dialog with the title: `Layer: xxx` -- the auto-sizing thing uses anything before a : for encoding the size, and this ensures that you don't have to keep resizing your layer windows.  So somehow your code is not up-to-date with that change, which was a while ago.  this is in `emergent/netview/layname.go`.  definitely fix that first!

**Comment by rohrlich** [comment]
first: I update my code every morning so I went looking elsewhere for the problem and found it!
RunProj from gide was pointed at the wrong directory! I through away my command prefs file which was very old and RunProj is now running the correct executable and all of the netview code is working well.
