### ISSUE TITLE
command to execute ra25 after build doesn't work

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#5]
Following the Wiki Install instructions I successfully installed and built the ra25 example, but when I used the command
./ra25 it told me file not found. 
 However, if I used the full pathname it worked. The path to the executable is somehow not being set.  How to set it should probably be part of the Install instructions.

**Comment by rcoreilly** [comment]
you might not have been in the right directory?  I can't think of a way that typing ./ra25 wouldn't work if there is an executable named "ra25" right there in the same directory..

**Comment by StephenJRead** [comment]
Okay will check and see.

Sent from my iPhone

On May 9, 2019, at 10:24 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


you might not have been in the right directory? I can't think of a way that typing ./ra25 wouldn't work if there is an executable named "ra25" right there in the same directory..

**Comment by StephenJRead** [comment]
Okay. I wasn’t in the ra25 directory.  I was 1 level up.  Once I cd’d into ra25 it worked.


On May 9, 2019, at 10:24 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


you might not have been in the right directory? I can't think of a way that typing ./ra25 wouldn't work if there is an executable named "ra25" right there in the same directory..
