### ISSUE TITLE
Blockupdates is blocking updates! Netview not updating.

### ISSUE THREAD

**Issue by rohrlich** [emer/emergent#50]
Commenting out Blockupdates in this code gets my simulation running again.

func (nv *NetView) GoUpdate() {
	if !nv.IsVisible() || !nv.HasLayers() {
		return
	}
	if nv.Viewport.IsUpdatingNode() {
		return
	}
	//nv.Viewport.BlockUpdates()
	vs := nv.Scene()
	updt := vs.UpdateStart()
	nv.UpdateImpl()
	//nv.Viewport.UnblockUpdates()
	vs.UpdateEnd(updt)
}

**Comment by rcoreilly** [comment]
yikes -- I didn't realize this was actually used anywhere!  I'll re-disable it in the main code and remove it from all my code..

**Comment by rcoreilly** [comment]
actually I will just remove these methods for now and that will ensure people remove the calls..  doesn't seem to be the right way to do this so better to just remove for now.

**Comment by rcoreilly** [comment]
And I just had another idea that is now pushed: set the updating flag which prevents other updates -- this at least doesn't completely block everything and can now be tried in your other case..
