### ISSUE TITLE
hip project build from source error

### ISSUE THREAD

**Issue by andreifoldes** [emer/emergent#62]
Greetings,

When trying to build the` sims\ch8\hip ` I get the following error:
I recently installed and have the emergent@v1.1.6 on board.
```
.\hip.go:707:19: ecout.UnitVarIdx undefined (type *leabra.Layer has no field or method UnitVarIdx)
.\hip.go:708:19: ecout.UnitVarIdx undefined (type *leabra.Layer has no field or method UnitVarIdx)
.\hip.go:709:20: ecout.UnitVarIdx undefined (type *leabra.Layer has no field or method UnitVarIdx)
```

**Comment by rcoreilly** [comment]
I'm able to replicate this, using the current go.mod.  I've been holding off updating based on a number of ongoing changes in the emergent code -- will update sims later tonight so it will build everything.  ch10/sir will still be broken for a while though.

**Comment by rcoreilly** [comment]
now fixed.
