### ISSUE TITLE
Clicking on a layer in NetView when the layer has Off=true leads to reliable crash 

### ISSUE THREAD

**Issue by rohrlich** [emer/emergent#67]

**Comment by rcoreilly** [comment]
I wasn't able to replicate on ra25 or sims/ch9/dyslex with a lesion to various layers that just turns the Off flag on..  can you provide steps to replicate?

**Comment by rohrlich** [comment]
Hmmm, I just reproduced the problem on ra25.

 	out := net.AddLayer2D("Output", 5, 5, emer.Target)
	out.SetOff(true)

just click on any unit of the Output layer

rohrlich@MacBook-Pro-5:ra25:> ./ra25
panic: runtime error: index out of range [6] with length 0

goroutine 20 [running]:
github.com/emer/leabra/leabra.(*Prjn).SynIdx(0xc0006a0c80, 0x0, 0x6, 0x0)
	/Users/rohrlich/go/src/github.com/emer/leabra/leabra/prjn.go:88 +0xd6
github.com/emer/leabra/leabra.(*Prjn).SynVal(0xc0006a0c80, 0xc0004841a2, 0x2, 0x0, 0x6, 0x0)
	/Users/rohrlich/go/src/github.com/emer/leabra/leabra/prjn.go:158 +0x9b
github.com/emer/leabra/leabra.(*Layer).SendPrjnVals(0xc000635c00, 0xc0004a1760, 0xc0004841a2, 0x2, 0x54fd9a0, 0xc0006ce000, 0x6, 0x0, 0x0, 0x54b3c40, ...)
	/Users/rohrlich/go/src/github.com/emer/leabra/leabra/layer.go:280 +0x19a
github.com/emer/emergent/netview.(*NetData).Record(0xc0007ab620, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/emer/emergent/netview/netdata.go:143 +0x5f3
github.com/emer/emergent/netview.(*NetView).Record(0xc0007ab000, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/emer/emergent/netview/netview.go:106 +0xe5
github.com/emer/emergent/netview.(*LayObj).ConnectEvents3D.func1(0x5526bc0, 0xc00092ed80, 0x5532140, 0xc000f0a000, 0x0, 0x511a5a0, 0xc00a1ee880)
	/Users/rohrlich/go/src/github.com/emer/emergent/netview/layobj.go:74 +0x32d
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc00063fd28, 0x5532140, 0xc000f0a000, 0x0, 0x511a5a0, 0xc00a1ee880)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000f0a198, 0x54da3e0, 0xc00a1ee880, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:225 +0x39a
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000f0a000, 0x54da3e0, 0xc00a1ee880)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1547 +0x8d1
github.com/goki/gi/gi.(*Window).EventLoop(0xc000f0a000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1469 +0x36
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000f0a000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:867 +0x6d
main.guirun()
	/Users/rohrlich/go/src/github.com/emer/leabra/examples/ra25/ra25.go:58 +0x4b
main.main.func1()
	/Users/rohrlich/go/src/github.com/emer/leabra/examples/ra25/ra25.go:50 +0x20
github.com/goki/gi/gimain.Main.func1(0x54ee9e0, 0x6946ce0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:31 +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/app.go:87 +0x40
created by github.com/goki/gi/oswin/driver/glos.Main
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/app.go:86 +0x87
rohrlich@MacBook-Pro-5:ra25:>

**Comment by rcoreilly** [comment]
Only happens when you turn off prior to building!  added guard.
