### ISSUE TITLE
Network display overwrites controls

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#8]
Note that in this screenshot the network graph overwrites the controls at the bottom of the window.

<img width="1508" alt="Screen Shot 2019-05-13 at 12 02 18 PM" src="https://user-images.githubusercontent.com/21046859/57647223-43c43180-7577-11e9-8b19-1650e2b79aa3.png">

**Comment by rcoreilly** [comment]
thanks for reporting -- had noticed too -- just fixed in new gogi/gi push.
