### ISSUE TITLE
looper is resetting the counters before calling OnEnd

### ISSUE THREAD

**Issue by rcoreilly** [emer/emergent#86]
For SaveWeights, it is supposed to set the filename to the epoch at which the weights are being saved.

**Comment by rcoreilly** [comment]
@qemqemqem could you look into this?

**Comment by qemqemqem** [comment]
Counters are being reset at this point, which is after OnEnd functions are
called: https://github.com/emer/emergent/blob/master/looper/manager.go#L257

What evidence do you see that they're being reset at the wrong time?

Andrew

**Comment by rcoreilly** [comment]
do this:
```
$ ./ra25 -nogui -tag=test -wts -runs=1 -epochs=10
```
observe the .wts file name is not numbered with 0010 at the end, as it should have been.

**Comment by rcoreilly** [comment]
I traced it in the debugger but not extensively..

**Comment by rcoreilly** [comment]
I added this test in `step_test` -- it is failing..  should provide a good debug target.

```Go
	manager.GetLoop(etime.Train, etime.Run).OnEnd.Add("Counters Test", func() {
		run := manager.Stacks[etime.Train].Loops[etime.Run].Counter.Cur
		epc := manager.Stacks[etime.Train].Loops[etime.Epoch].Counter.Cur
		if epc != 5 {
			t.Errorf("Run %d OnEnd epoch counter should be 5, not: %d", run, epc)
		}
	})
```

**Comment by rcoreilly** [comment]
@qemqemqem just making sure this is on your radar -- not exactly a blocker but definitely affects functionality of looper..

**Comment by qemqemqem** [comment]
Fixed with https://github.com/emer/emergent/commit/7de7b2223a782705ccd45a667abd56b9871529cc
