### ISSUE TITLE
Save buttons erratic in EpcPlot window

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#9]
After running a training session if I click on the various buttons in the EpcPlot window to Save weights, Save SVG, etc.  I get erratic responses.  Sometimes it gives me the dialog box, but other times it gives me an entirely black panel or it totally freezes the simulator, or it crashes.

**Comment by rcoreilly** [comment]
I really don't know how this issue hadn't appeared before -- some really basic issues broken in closing windows -- now fixed (hopefully) in gogi/gi .  May be some residual issues but I'll be on the lookout and will fix as I find.

**Comment by StephenJRead** [comment]
So presumably I need to update and re build gogi?


On May 13, 2019, at 2:13 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I really don't know how this issue hadn't appeared before -- some really basic issues broken in closing windows -- now fixed (hopefully) in gogi/gi . May be some residual issues but I'll be on the lookout and will fix as I find.
